// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQmo__uYXEGCoUGm4V11tPKbFfBjKwvZs',
    appId: '1:57412847350:web:e79525a0c657e1720a0ed7',
    messagingSenderId: '57412847350',
    projectId: 'bookstoreapp-67bd1',
    authDomain: 'bookstoreapp-67bd1.firebaseapp.com',
    storageBucket: 'bookstoreapp-67bd1.appspot.com',
    measurementId: 'G-DYWKR7TZLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf6cCwLOdgUAzYbc8rLfRjJA5v1fURyH0',
    appId: '1:57412847350:android:79e4b311cf5aca710a0ed7',
    messagingSenderId: '57412847350',
    projectId: 'bookstoreapp-67bd1',
    storageBucket: 'bookstoreapp-67bd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk0zXUeiDIMH3NAiQEE8tVYfvCMwKxrLw',
    appId: '1:57412847350:ios:0151245707f1f2690a0ed7',
    messagingSenderId: '57412847350',
    projectId: 'bookstoreapp-67bd1',
    storageBucket: 'bookstoreapp-67bd1.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk0zXUeiDIMH3NAiQEE8tVYfvCMwKxrLw',
    appId: '1:57412847350:ios:0151245707f1f2690a0ed7',
    messagingSenderId: '57412847350',
    projectId: 'bookstoreapp-67bd1',
    storageBucket: 'bookstoreapp-67bd1.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQmo__uYXEGCoUGm4V11tPKbFfBjKwvZs',
    appId: '1:57412847350:web:db69fcf9d20ae1070a0ed7',
    messagingSenderId: '57412847350',
    projectId: 'bookstoreapp-67bd1',
    authDomain: 'bookstoreapp-67bd1.firebaseapp.com',
    storageBucket: 'bookstoreapp-67bd1.appspot.com',
    measurementId: 'G-VGQCCNJ306',
  );
}
